default: &default
  adapter: postgresql
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL') %>
  timeout: 5000

development:
  <<: *default
  database: qr_challenge_development

test:
  <<: *default
  database: qr_challenge_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: qr_challenge
